apiVersion: batch/v1
kind: Job
metadata:
  name: {STORY_ID}-add-images-to-story
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
        - name: add-images-to-story
          image: us.gcr.io/$ARTEFACTS_PROJECT_NAME/video-composer
          command: ["bash", "-c",
                    "mkdir /library && \
                     gcsfuse \
                       --implicit-dirs \
                       $LIBRARY_BUCKET_NAME \
                       /library && \
                     python3 add_images.py && \
                     gcloud pubsub topics publish completed-add-images-to-story \
                       --message \"{STORY_ID}\""]
          workingDir: /app
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          resources:
            limits:
              cpu: "$NUM_CPUS"
      restartPolicy: Never
