apiVersion: batch/v1
kind: Job
metadata:
  name: {STORY_ID}-presenter-bg
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
        - name: add-presenter-bg
          image: us.gcr.io/$ARTEFACTS_PROJECT_NAME/video-composer
          env:
            - name: AUDIO_CODEC
              value: "$AUDIO_CODEC"
            - name: AUDIO_FMT
              value: "$AUDIO_FMT"
            - name: FPS
              value: "$FPS"
            - name: IMG_FMT
              value: "$IMG_FMT"
            - name: PIXEL_FMT
              value: "$PIXEL_FMT"
            - name: VIDEO_CODEC
              value: "$VIDEO_CODEC"
            - name: VIDEO_FMT
              value: "$VIDEO_FMT"
          command: ["bash", "-c",
                    "echo add-presenter-bg `date` >> /data/events.log && \
                     mkdir /library && \
                     gcsfuse \
                       --implicit-dirs \
                       $LIBRARY_BUCKET_NAME \
                       /library && \
                     python3 add_presenter_bg.py && \
                     gcloud pubsub topics publish completed-add-presenter-bg \
                       --message \"{STORY_ID}\" && \
                     echo add-presenter-bg `date` >> /data/events.log"]
          workingDir: /app
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          resources:
            limits:
              cpu: "$NUM_CPUS"
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: {STORY_ID}
      restartPolicy: Never
      volumes:
        - name: data
          hostPath:
            path: /mnt/disks/ssd0
