apiVersion: batch/v1
kind: Job
metadata:
  name: {STORY_ID}-add-audio-to-story
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
        - name: add-audio-to-story
          image: us.gcr.io/$ARTEFACTS_PROJECT_NAME/video-composer
          env:
            - name: AUDIO_CODEC
              value: "$AUDIO_CODEC"
            - name: AUDIO_FMT
              value: "$AUDIO_FMT"
            - name: FPS
              value: "$FPS"
            - name: IMG_FMT
              value: "$IMG_FMT"
            - name: PIXEL_FMT
              value: "$PIXEL_FMT"
            - name: VIDEO_CODEC
              value: "$VIDEO_CODEC"
            - name: VIDEO_FMT
              value: "$VIDEO_FMT"
          command: ["bash", "-c",
                    "echo add-audio-to-story `date` >> /data/events.log && \
                     ffmpeg \
                       -y \
                       -i /data/audio.$AUDIO_FMT \
                       -i /data/story-no-audio.$VIDEO_FMT \
                       -c:a $AUDIO_CODEC \
                       -c:v $VIDEO_CODEC \
                       -pix_fmt $PIXEL_FMT \
                       /data/story-with-audio.$VIDEO_FMT && \
                     gcloud pubsub topics publish completed-add-audio-to-story \
                       --message \"{STORY_ID}\" && \
                     echo add-audio-to-story `date` >> /data/events.log"]
          resources:
            limits:
              cpu: "$NUM_CPUS"
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: {STORY_ID}
      restartPolicy: Never
      volumes:
        - name: data
          hostPath:
            path: /mnt/disks/ssd0
