apiVersion: batch/v1
kind: Job
metadata:
  name: {STORY_ID}-add-bg-to-story
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
        - name: add-bg-to-story
          image: us.gcr.io/plasmic/video-composer
          command: ["bash", "-c",
                    "mkdir /data && \
                     mkdir /library && \
                     gcsfuse \
                       --only-dir {STORY_ID} \
                       $GENERATED_BUCKET_NAME \
                       /data && \
                     gcsfuse \
                       --implicit-dirs \
                       $LIBRARY_BUCKET_NAME \
                       /library && \
                     python3 add_bg.py && \
                     gcloud pubsub topics publish completed-add-bg-to-story \
                       --message \"{STORY_ID}\""]
          workingDir: /app
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
      restartPolicy: Never
