apiVersion: batch/v1
kind: Job
metadata:
  name: {STORY_ID}-add-audio-to-video
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
        - name: add-audio-to-video
          image: us.gcr.io/plasmic/render-video
          command: ["bash", "-c",
                    "mkdir /data && \
                     gcsfuse -o nonempty --only-dir {STORY_ID} $GCS_BUCKET_NAME /data && \
                     ffmpeg \
                       -y \
                       -i /data/no-audio.$VIDEO_FMT \
                       -i /data/audio.wav \
                       -c:v copy \
                       -strict experimental \
                       -c:a $AUDIO_CODEC \
                       /data/video.$VIDEO_FMT && \
                     gcloud pubsub topics publish completed-add-audio-to-video \
                       --message \"{STORY_ID}\""]
          workingDir: /app
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
      restartPolicy: Never
