apiVersion: batch/v1
kind: Job
metadata:
  name: {STORY_ID}-add-audio-to-story
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
        - name: add-audio-to-story
          image: us.gcr.io/plasmic/render-video
          command: ["bash", "-c",
                    "mkdir /data && \
                     gcsfuse \
                       --only-dir {STORY_ID} \
                       $GENERATED_BUCKET_NAME \
                       /data && \
                     ffmpeg \
                       -y \
                       -i /data/audio.wav \
                       -i /data/story-no-audio.$VIDEO_FMT \
                       -c:a copy \
                       -c:v $VIDEO_CODEC \
                       -pix_fmt $PIXEL_FMT \
                       /data/story-with-audio.$VIDEO_FMT && \
                     gcloud pubsub topics publish completed-add-audio-to-story \
                       --message \"{STORY_ID}\""]
          workingDir: /app
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
      restartPolicy: Never
