apiVersion: batch/v1
kind: Job
metadata:
  name: {STORY_ID}-add-dynamic-overlay-to-story
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
        - name: add-dynamic-overlay-to-story
          image: us.gcr.io/$ARTEFACTS_PROJECT_NAME/video-composer
          command: ["bash", "-c",
                    "echo add-dynamic-overlay-to-story `date` >> /data/events.log && \
                     python3 add_dynamic_overlay.py && \
                     gsutil -m rsync -r /data gs://${GENERATED_BUCKET_NAME}/{STORY_ID} && \
                     gcloud pubsub topics publish completed-add-dynamic-overlay-to-story \
                       --message \"{STORY_ID}\" && \
                     echo add-dynamic-overlay-to-story `date` >> /data/events.log"]
          workingDir: /app
          resources:
            limits:
              cpu: "$NUM_CPUS"
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: {STORY_ID}
      restartPolicy: Never
      volumes:
        - name: data
          hostPath:
            path: /mnt/disks/ssd0
