apiVersion: batch/v1
kind: Job
metadata:
  name: {STORY_ID}-add-audio-to-story
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
        - name: add-audio-to-story
          image: us.gcr.io/$ARTEFACTS_PROJECT_NAME/video-composer
          command: ["bash", "-c",
                    "ffmpeg \
                       -y \
                       -i /data/audio.$AUDIO_FMT \
                       -i /data/story-no-audio.$VIDEO_FMT \
                       -c:a $AUDIO_CODEC \
                       -c:v $VIDEO_CODEC \
                       -pix_fmt $PIXEL_FMT \
                       /data/story-with-audio.$VIDEO_FMT && \
                     gsutil -m rsync -r /data gs://${GENERATED_BUCKET_NAME}/{STORY_ID} && \
                     gcloud pubsub topics publish completed-add-audio-to-story \
                       --message \"{STORY_ID}\""]
          resources:
            limits:
              cpu: "$NUM_CPUS"
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: {STORY_ID}
      restartPolicy: Never
      volumes:
        - name: data
          hostPath:
            path: /mnt/disks/ssd0
