apiVersion: batch/v1
kind: Job
metadata:
  name: {STORY_ID}-align-frames
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
        - name: align-frames
          image: us.gcr.io/$ARTEFACTS_PROJECT_NAME/align-face
          env:
            - name: IMG_FMT
              value: "$IMG_FMT"
          command: ["bash", "-c",
                    "echo align-frames `date` >> /data/events.log && \
                     python3 align_frames.py && \
                     gcloud pubsub topics publish completed-align-frames \
                       --message \"{STORY_ID}\" && \
                     echo align-frames `date` >> /data/events.log"]
          workingDir: /app
          resources:
            limits:
              cpu: "$NUM_CPUS"
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: {STORY_ID}
      restartPolicy: Never
      volumes:
        - name: data
          hostPath:
            path: /mnt/disks/ssd0
