apiVersion: batch/v1
kind: Job
metadata:
  name: {STORY_ID}-animate-anchor
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
        - name: animate-anchor
          image: us.gcr.io/$ARTEFACTS_PROJECT_NAME/video-composer
          env:
            - name: AUDIO_CODEC
              value: "$AUDIO_CODEC"
            - name: AUDIO_FMT
              value: "$AUDIO_FMT"
            - name: FPS
              value: "$FPS"
            - name: IMG_FMT
              value: "$IMG_FMT"
            - name: PIXEL_FMT
              value: "$PIXEL_FMT"
            - name: VIDEO_CODEC
              value: "$VIDEO_CODEC"
            - name: VIDEO_FMT
              value: "$VIDEO_FMT"
          command: ["bash", "-c",
                    "echo animate-anchor `date` >> /data/events.log && \
                     python3 animate_anchor.py && \
                     gcloud pubsub topics publish completed-animate-anchor \
                       --message \"{STORY_ID}\" && \
                     echo animate-anchor `date` >> /data/events.log"]
          workingDir: /app
          resources:
            limits:
              cpu: "$NUM_CPUS"
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: {STORY_ID}
      restartPolicy: Never
      volumes:
        - name: data
          hostPath:
            path: /mnt/disks/ssd0
