apiVersion: batch/v1
kind: Job
metadata:
  name: {STORY_ID}-captions-generator
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
        - name: captions-generator
          image: us.gcr.io/$ARTEFACTS_PROJECT_NAME/captions-generator
          command: ["bash", "-c",
                    "echo captions-generator `date` >> /data/events.log && \
                     python3 captions.py && \
                     gsutil copy /data/captions.vtt gs://${GENERATED_BUCKET_NAME}/{STORY_ID}/captions.vtt && \
                     gcloud pubsub topics publish completed-captions-generator \
                       --message \"{STORY_ID}\" && \
                     echo captions-generator `date` >> /data/events.log"]
          workingDir: /app
          resources:
            limits:
              cpu: "$NUM_CPUS"
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: {STORY_ID}
      restartPolicy: Never
      volumes:
        - name: data
          hostPath:
            path: /mnt/disks/ssd0
