apiVersion: batch/v1
kind: Job
metadata:
  name: {STORY_ID}-end-story
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
        - name: end-story
          image: us.gcr.io/$ARTEFACTS_PROJECT_NAME/video-composer
          command: ["bash", "-c",
                    "echo end-story `date` >> /data/events.log && \
                     gsutil copy /data/normalized-story.mp4   gs://${GENERATED_BUCKET_NAME}/{STORY_ID}/ && \
                     gsutil copy /data/dynamic-overlay.mp4    gs://${GENERATED_BUCKET_NAME}/{STORY_ID}/ && \
                     gsutil copy /data/composed-story.mp4     gs://${GENERATED_BUCKET_NAME}/{STORY_ID}/ && \
                     gsutil copy /data/story.yaml             gs://${GENERATED_BUCKET_NAME}/{STORY_ID}/ && \
                     rm -rf /data/* && \
                     gcloud pubsub topics publish completed-end-story \
                       --message \"{STORY_ID}\" && \
                     echo end-story `date` >> /data/events.log"]
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: {STORY_ID}
      restartPolicy: Never
      volumes:
        - name: data
          hostPath:
            path: /mnt/disks/ssd0
