apiVersion: batch/v1
kind: Job
metadata:
  name: {STORY_ID}-extract-landmarks
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
        - name: extract-landmarks
          image: us.gcr.io/$ARTEFACTS_PROJECT_NAME/align-face
          env:
            - name: IMG_FMT
              value: "$IMG_FMT"
          command: ["bash", "-c",
                    "echo extract-landmarks `date` >> /data/events.log && \
                     mkdir /models && \
                     gcsfuse \
                       --implicit-dirs \
                       $MODELS_BUCKET_NAME \
                       /models && \
                     python3 extract_landmarks.py && \
                     gcloud pubsub topics publish completed-extract-landmarks \
                       --message \"{STORY_ID}\" && \
                     echo extract-landmarks `date` >> /data/events.log"]
          workingDir: /app
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          resources:
            limits:
              cpu: "$NUM_CPUS"
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: {STORY_ID}
      restartPolicy: Never
      volumes:
        - name: data
          hostPath:
            path: /mnt/disks/ssd0
