apiVersion: batch/v1
kind: Job
metadata:
  name: {STORY_ID}-images-to-video
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
        - name: images-to-video
          image: us.gcr.io/$ARTEFACTS_PROJECT_NAME/video-composer
          command: ["bash", "-c",
                    "echo images-to-video `date` >> /data/events.log && \
                     ffmpeg \
                       -y \
                       -framerate $FPS \
                       -i /data/frames/%010d.$IMG_FMT \
                       -c:v $VIDEO_CODEC \
                       -pix_fmt $PIXEL_FMT \
                       /data/story-no-audio.$VIDEO_FMT && \
                     gcloud pubsub topics publish completed-images-to-video \
                       --message \"{STORY_ID}\" && \
                     echo images-to-video `date` >> /data/events.log"]
          resources:
            limits:
              cpu: "$NUM_CPUS"
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: {STORY_ID}
      restartPolicy: Never
      volumes:
        - name: data
          hostPath:
            path: /mnt/disks/ssd0
