apiVersion: batch/v1
kind: Job
metadata:
  name: {STORY_ID}-images-to-video
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
        - name: images-to-video
          image: us.gcr.io/$ARTEFACTS_PROJECT_NAME/render-video
          command: ["bash", "-c",
                    "ffmpeg \
                       -y \
                       -framerate $FPS \
                       -i /data/inferred/%010d.$IMG_FMT \
                       -c:v $VIDEO_CODEC \
                       -pix_fmt $PIXEL_FMT \
                       /data/story-no-audio.$VIDEO_FMT && \
                     gcloud pubsub topics publish completed-images-to-video \
                       --message \"{STORY_ID}\""]
          workingDir: /app
          resources:
            limits:
              cpu: "$NUM_CPUS"
      restartPolicy: Never
