apiVersion: batch/v1
kind: Job
metadata:
  name: {STORY_ID}-init-story
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
        - name: init-story
          image: us.gcr.io/$ARTEFACTS_PROJECT_NAME/render-video
          command: ["bash", "-c",
                    "mkdir -p /data/inference && \
                     mkdir -p /data/inferred && \
                     mkdir -p /data/landmarks && \
                     gsutil -m cp -r gs://${GENERATED_BUCKET_NAME}/{STORY_ID}/* /data && \
                     gcloud pubsub topics publish completed-init-story \
                       --message \"{STORY_ID}\""]
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: {STORY_ID}
      restartPolicy: Never
      volumes:
        - name: data
          hostPath:
            path: /mnt/disks/ssd0
