apiVersion: batch/v1
kind: Job
metadata:
  name: {STORY_ID}-init-story
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
        - name: init-story
          image: us.gcr.io/plasmic/init-story
          env:
            - name: GCS_BUCKET_NAME
              value: "$GCS_BUCKET_NAME"
            - name: STORY_ID
              value: "{STORY_ID}"
          command: ["bash", "-c",
                    "python3 init_story.py && \
                     gcloud pubsub topics publish completed-init-story \
                       --message \"{STORY_ID}\""]
          workingDir: /app
      restartPolicy: Never
