apiVersion: batch/v1
kind: Job
metadata:
  name: {STORY_ID}-init-story
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
        - name: init-story
          image: us.gcr.io/$ARTEFACTS_PROJECT_NAME/video-composer
          env:
            - name: AUDIO_CODEC
              value: "$AUDIO_CODEC"
            - name: AUDIO_FMT
              value: "$AUDIO_FMT"
            - name: FPS
              value: "$FPS"
            - name: IMG_FMT
              value: "$IMG_FMT"
            - name: PIXEL_FMT
              value: "$PIXEL_FMT"
            - name: VIDEO_CODEC
              value: "$VIDEO_CODEC"
            - name: VIDEO_FMT
              value: "$VIDEO_FMT"
          command: ["bash", "-c",
                    "echo init-story `date` >> /data/events.log && \
                     mkdir -p /data/aligned && \
                     mkdir -p /data/frames && \
                     mkdir -p /data/html-capture && \
                     mkdir -p /data/inference && \
                     mkdir -p /data/inferred && \
                     mkdir -p /data/landmarks && \
                     gsutil -m cp -r gs://${GENERATED_BUCKET_NAME}/{STORY_ID}/* /data && \
                     gcloud pubsub topics publish completed-init-story \
                       --message \"{STORY_ID}\" && \
                     echo init-story `date` >> /data/events.log"]
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: {STORY_ID}
      restartPolicy: Never
      volumes:
        - name: data
          hostPath:
            path: /mnt/disks/ssd0
