apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jobs-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobs-manager
  template:
    metadata:
      labels:
        app: jobs-manager
    spec:
      serviceAccountName: jobs-manager
      containers:
        - name: jobs-manager
          image: us.gcr.io/$ARTEFACTS_PROJECT_NAME/generate-jobs-manager
          command: ["bash", "-c", "python3 jobs_manager.py"]
          workingDir: /app
          env:
            - name: ARTEFACTS_PROJECT_NAME
              value: "$ARTEFACTS_PROJECT_NAME"
            - name: AUDIO_CODEC
              value: "$AUDIO_CODEC"
            - name: COMPUTE_PROJECT_NAME
              value: "$COMPUTE_PROJECT_NAME"
            - name: FPS
              value: "$FPS"
            - name: GENERATED_BUCKET_NAME
              value: "$GENERATED_BUCKET_NAME"
            - name: LIBRARY_BUCKET_NAME
              value: "$LIBRARY_BUCKET_NAME"
            - name: MODELS_BUCKET_NAME
              value: "$MODELS_BUCKET_NAME"
            - name: PIXEL_FMT
              value: "$PIXEL_FMT"
            - name: REDIS_HOST
              value: "$REDIS_HOST"
            - name: REDIS_PORT
              value: "$REDIS_PORT"
            - name: TEXT_TO_SPEC_SIGMA
              value: "$TEXT_TO_SPEC_SIGMA"
            - name: TEXT_TO_SPEC_SAMPLE_RATE
              value: "$TEXT_TO_SPEC_SAMPLE_RATE"
            - name: TEXT_TO_SPEC_STRENGTH
              value: "$TEXT_TO_SPEC_STRENGTH"
            - name: VIDEO_CODEC
              value: "$VIDEO_CODEC"
            - name: VIDEO_FMT
              value: "$VIDEO_FMT"
