apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jobs-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobs-manager
  template:
    metadata:
      labels:
        app: jobs-manager
    spec:
      serviceAccountName: jobs-manager
      containers:
        - name: jobs-manager
          image: us.gcr.io/$ARTEFACTS_PROJECT_NAME/generate-jobs-manager
          env:
            - name: ARTEFACTS_PROJECT_NAME
              value: "$ARTEFACTS_PROJECT_NAME"
            - name: AUDIO_CODEC
              value: "$AUDIO_CODEC"
            - name: AUDIO_FMT
              value: "$AUDIO_FMT"
            - name: COMPUTE_PROJECT_NAME
              value: "$COMPUTE_PROJECT_NAME"
            - name: FPS
              value: "$FPS"
            - name: GENERATED_BUCKET_NAME
              value: "$GENERATED_BUCKET_NAME"
            - name: HTML_CAPTURE_DURATION
              value: "$HTML_CAPTURE_DURATION"
            - name: HTML_CAPTURE_URL
              value: "$HTML_CAPTURE_URL"
            - name: IMG_FMT
              value: "$IMG_FMT"
            - name: LIBRARY_BUCKET_NAME
              value: "$LIBRARY_BUCKET_NAME"
            - name: MODELS_BUCKET_NAME
              value: "$MODELS_BUCKET_NAME"
            - name: NUM_CPUS
              value: "$NUM_CPUS"
            - name: PIXEL_FMT
              value: "$PIXEL_FMT"
            - name: TEXT_TO_SPEC_SIGMA
              value: "$TEXT_TO_SPEC_SIGMA"
            - name: TEXT_TO_SPEC_SAMPLE_RATE
              value: "$TEXT_TO_SPEC_SAMPLE_RATE"
            - name: TEXT_TO_SPEC_STRENGTH
              value: "$TEXT_TO_SPEC_STRENGTH"
            - name: VIDEO_CODEC
              value: "$VIDEO_CODEC"
            - name: VIDEO_FMT
              value: "$VIDEO_FMT"
          command: ["bash", "-c", "python3 jobs_manager.py"]
          workingDir: /app
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          hostPath:
            path: /mnt/disks/ssd0
