apiVersion: batch/v1
kind: Job
metadata:
  name: {STORY_ID}-normalize-audio
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
        - name: normalize-audio
          image: us.gcr.io/$ARTEFACTS_PROJECT_NAME/video-composer
          command: ["bash", "-c",
                    "echo normalize-audio `date` >> /data/events.log && \
                     python3 normalize_audio.py && \
                     gsutil -m rsync -r /data gs://${GENERATED_BUCKET_NAME}/{STORY_ID} && \
                     gcloud pubsub topics publish completed-normalize-audio \
                       --message \"{STORY_ID}\" && \
                     echo normalize-audio `date` >> /data/events.log"]
          workingDir: /app
          resources:
            limits:
              cpu: "$NUM_CPUS"
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: {STORY_ID}
      restartPolicy: Never
      volumes:
        - name: data
          hostPath:
            path: /mnt/disks/ssd0
