apiVersion: batch/v1
kind: Job
metadata:
  name: {STORY_ID}-pix-to-pix
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
        - name: pix-to-pix
          image: us.gcr.io/plasmic/pix-to-pix
          command: ["bash", "-c",
                    "mkdir /data && \
                     mkdir /data/test_A && \
                     mkdir /data/inferred && \
                     mkdir /models && \
                     gcsfuse \
                       --only-dir {STORY_ID}/inference \
                       $GENERATED_BUCKET_NAME \
                       /data/test_A && \
                     gcsfuse \
                       --only-dir {STORY_ID}/inferred \
                       $GENERATED_BUCKET_NAME \
                       /data/inferred && \
                     gcsfuse \
                       --implicit-dirs \
                       $MODELS_BUCKET_NAME \
                       /models && \
                     python3 inference.py && \
                     gcloud pubsub topics publish completed-pix-to-pix \
                       --message \"{STORY_ID}\""]
          workingDir: /app
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          resources:
            limits:
              nvidia.com/gpu: 1 # request 1 GPU
      restartPolicy: Never
