apiVersion: batch/v1
kind: Job
metadata:
  name: {STORY_ID}-pix-to-pix
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
        - name: pix-to-pix
          image: us.gcr.io/$ARTEFACTS_PROJECT_NAME/pix-to-pix
          command: ["bash", "-c",
                    "mkdir /models && \
                     gcsfuse \
                       --implicit-dirs \
                       $MODELS_BUCKET_NAME \
                       /models && \
                     python3 inference.py && \
                     gcloud pubsub topics publish completed-pix-to-pix \
                       --message \"{STORY_ID}\""]
          workingDir: /app
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          resources:
            limits:
              cpu: "$NUM_CPUS"
              nvidia.com/gpu: 1 # request 1 GPU
          volumeMounts:
            - mountPath: /data
              name: data
              subPath: {STORY_ID}
      restartPolicy: Never
      volumes:
        - name: data
          hostPath:
            path: /mnt/disks/ssd0
