apiVersion: batch/v1
kind: Job
metadata:
  name: {STORY_ID}-prepare-for-inference
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
        - name: prepare-for-inference
          image: us.gcr.io/$ARTEFACTS_PROJECT_NAME/speech-to-landmarks
          env:
            - name: AUDIO_CODEC
              value: "$AUDIO_CODEC"
            - name: AUDIO_FMT
              value: "$AUDIO_FMT"
            - name: FPS
              value: "$FPS"
            - name: IMG_FMT
              value: "$IMG_FMT"
            - name: PIXEL_FMT
              value: "$PIXEL_FMT"
            - name: VIDEO_CODEC
              value: "$VIDEO_CODEC"
            - name: VIDEO_FMT
              value: "$VIDEO_FMT"
          command: ["bash", "-c",
                    "echo prepare-for-inference `date` >> /data/events.log && \
                     mkdir /models && \
                     gcsfuse \
                       --implicit-dirs \
                       $MODELS_BUCKET_NAME \
                       /models && \
                     python3 prepare_for_inference.py && \
                     gcloud pubsub topics publish completed-prepare-for-inference \
                       --message \"{STORY_ID}\" && \
                     echo prepare-for-inference `date` >> /data/events.log"]
          workingDir: /app
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          resources:
            limits:
              cpu: "$NUM_CPUS"
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: {STORY_ID}
      restartPolicy: Never
      volumes:
        - name: data
          hostPath:
            path: /mnt/disks/ssd0
