apiVersion: batch/v1
kind: Job
metadata:
  name: {STORY_ID}-rotate-images
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
        - name: rotate-images
          image: us.gcr.io/$ARTEFACTS_PROJECT_NAME/video-composer
          env:
            - name: AUDIO_CODEC
              value: "$AUDIO_CODEC"
            - name: AUDIO_FMT
              value: "$AUDIO_FMT"
            - name: FPS
              value: "$FPS"
            - name: IMG_FMT
              value: "$IMG_FMT"
            - name: PIXEL_FMT
              value: "$PIXEL_FMT"
            - name: VIDEO_CODEC
              value: "$VIDEO_CODEC"
            - name: VIDEO_FMT
              value: "$VIDEO_FMT"
          command: ["bash", "-c",
                    "echo rotate-images `date` >> /data/events.log && \
                     ffmpeg \
                       -y \
                       -i /data/inferred/%010d.$IMG_FMT \
                       -vf transpose=1 \
                       /data/frames/%010d.$IMG_FMT && \
                     gcloud pubsub topics publish completed-rotate-video \
                       --message \"{STORY_ID}\" && \
                     echo rotate-images `date` >> /data/events.log"]
          workingDir: /app
          resources:
            limits:
              cpu: "$NUM_CPUS"
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: {STORY_ID}
      restartPolicy: Never
      volumes:
        - name: data
          hostPath:
            path: /mnt/disks/ssd0
