apiVersion: batch/v1
kind: Job
metadata:
  name: {STORY_ID}-rotate-images
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
        - name: rotate-images
          image: us.gcr.io/$ARTEFACTS_PROJECT_NAME/video-composer
          command: ["bash", "-c",
                    "echo rotate-images `date` >> /data/events.log && \
                     ffmpeg \
                       -y \
                       -i /data/inferred/%010d.$IMG_FMT \
                       -vf transpose=1 \
                       /data/frames/%010d.$IMG_FMT && \
                     gcloud pubsub topics publish completed-rotate-images \
                       --message \"{STORY_ID}\" && \
                     echo rotate-images `date` >> /data/events.log"]
          resources:
            limits:
              cpu: "$NUM_CPUS"
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: {STORY_ID}
      restartPolicy: Never
      volumes:
        - name: data
          hostPath:
            path: /mnt/disks/ssd0
