apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jobs-manager
rules:
  - apiGroups: ["", "batch"] # "" indicates the core API group
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jobs-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jobs-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jobs-manager
subjects:
  - kind: ServiceAccount
    name: jobs-manager
