apiVersion: batch/v1
kind: Job
metadata:
  name: {STORY_ID}-speech-to-landmarks
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
        - name: speech-to-landmarks
          image: us.gcr.io/$ARTEFACTS_PROJECT_NAME/speech-to-landmarks
          env:
            - name: AUDIO_FMT
              value: "$AUDIO_FMT"
            - name: FPS
              value: "$FPS"
            - name: IMG_FMT
              value: "$IMG_FMT"
          command: ["bash", "-c",
                    "echo speech-to-landmarks `date` >> /data/events.log && \
                     mkdir /models && \
                     gcsfuse \
                       --implicit-dirs \
                       $MODELS_BUCKET_NAME \
                       /models && \
                     python3 speech_to_landmarks.py && \
                     gcloud pubsub topics publish completed-speech-to-landmarks \
                       --message \"{STORY_ID}\" && \
                     gcloud pubsub topics publish completed-speech-to-landmarks-2 \
                       --message \"{STORY_ID}\" && \
                     echo speech-to-landmarks `date` >> /data/events.log"]
          workingDir: /app
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          resources:
            limits:
              cpu: "$NUM_CPUS"
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: {STORY_ID}
      restartPolicy: Never
      volumes:
        - name: data
          hostPath:
            path: /mnt/disks/ssd0
