apiVersion: batch/v1
kind: Job
metadata:
  name: {STORY_ID}-text-to-spec
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
        - name: text-to-spec
          image: us.gcr.io/$ARTEFACTS_PROJECT_NAME/text-to-spec
          env:
            - name: AUDIO_CODEC
              value: "$AUDIO_CODEC"
            - name: AUDIO_FMT
              value: "$AUDIO_FMT"
            - name: SAMPLE_RATE
              value: "$TEXT_TO_SPEC_SAMPLE_RATE"
            - name: SIGMA
              value: "$TEXT_TO_SPEC_SIGMA"
            - name: STRENGTH
              value: "$TEXT_TO_SPEC_STRENGTH"
          command: ["bash", "-c",
                    "echo text-to-spec `date` >> /data/events.log && \
                     mkdir /models && \
                     gcsfuse \
                       --implicit-dirs \
                       $MODELS_BUCKET_NAME \
                       /models && \
                     python3 inference.py && \
                     gcloud pubsub topics publish completed-text-to-spec \
                       --message \"{STORY_ID}\" && \
                     echo text-to-spec `date` >> /data/events.log"]
          workingDir: /app
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          resources:
            limits:
              cpu: "$NUM_CPUS"
              nvidia.com/gpu: 1 # request 1 GPU
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: {STORY_ID}
      restartPolicy: Never
      volumes:
        - name: data
          hostPath:
            path: /mnt/disks/ssd0
